fix

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -57,11 +57,13 @@ jobs:
       - name: "test | check if container is ready"
         working-directory: "${{matrix.workdir}}"
         run: |
+          set -xe
           __RETRY=10
           for i in $(seq 1 $__RETRY); do
               __CONTAINER_JSON=$(docker inspect ${{matrix.workdir}}__${{github.sha}})
-              __CONTAINER_READINESS=$(echo $container_json | jq '.[0].State.Health.Status')
-              if [[ $readiness_status == "\"healthy\"" ]]; then
+              __CONTAINER_READINESS=$(echo $__CONTAINER_JSON | jq '.[0].State.Health.Status')
+              [[ -z $__CONTAINER_READINESS ]] && echo "cannot get container readiness" && exit 1
+              if [[ $__CONTAINER_READINESS == healthy ]]; then
                   __CONTAINER_PORT=$(echo $__CONTAINER_JSON | jq '.[0].NetworkSettings.Ports["5000/tcp"][0].HostPort')
                   echo "Container is ready, listening on $__CONTAINER_PORT"
                   exit 0
