fix

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -62,7 +62,9 @@ jobs:
           for i in $(seq 1 $__RETRY); do
               __CONTAINER_JSON=$(docker inspect ${{matrix.workdir}}__${{github.sha}})
               __CONTAINER_READINESS=$(echo $__CONTAINER_JSON | jq '.[0].State.Health.Status')
-              [[ -z $__CONTAINER_READINESS ]] && echo "cannot get container readiness" && exit 1
+              [[ -z $__CONTAINER_READINESS ]] \
+                || [[$__CONTAINER_READINESS == null ]] \
+                && echo "cannot get container readiness" && exit 1
               if [[ $__CONTAINER_READINESS == healthy ]]; then
                   __CONTAINER_PORT=$(echo $__CONTAINER_JSON | jq '.[0].NetworkSettings.Ports["5000/tcp"][0].HostPort')
                   echo "Container is ready, listening on $__CONTAINER_PORT"
